### ISSUE TITLE
Can't Get Movies.AspNetCore to run

### ISSUE THREAD

**Issue by rmittelman** [DevZest/RDO.Net#1]
In Startup Class, ConfigureServices method, the following code causes an exception:

```
            services.AddMvc()
                .AddDataSetMvc()    // Add DataSet MVC support
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

```

The exception is:

`System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=DevZest.Data.AspNetCore
`

Also, in same class, I get a warning "IHostingEnvironment is obsolete"

**Comment by weifenluo** [comment]
The Movies.AspNetCore sample is targeting ASP.Net Core 2.2. Please make sure your Visual Studio has 2.2 SDK installed.

**Comment by rmittelman** [comment]
On the ASP.Net Core 2.2 download page it says "This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as .NET Core 3.1. See our support policy for more details.".  Even if I want to download it, I have no idea what version to download.  There is a 2.2.8, a 2.2.7, a 2.2.402, and many more.  Don't know which one to use.  I'm concerned because this seems obsolete.  Also, as mentioned before, the IHostingEnvironment is also marked as obsolete.  Please help.

**Comment by rmittelman** [comment]
There are no compile errors, just the run-time error mentioned above.  Also, when I did try to target ASP.Net Core 2.2, I got a bunch of errors.  Other components didn't like that. Microsoft.EntityFrameworkCore.SqlServer really didn't like it.  I couldn't find a version of that for core 2.2.  Will be happy to continue via email if you'll send me your address.  Thanks...

**Comment by weifenluo** [comment]
I'm working on this issue to target asp.net core 3.1 (the LTS version). It will take some time because there're a few breaking changes from 2.2 to 3.1:

JSON serializer/deserializer;
A few previously public class in using Microsoft.AspNetCore.Mvc.ViewFeatures.Internal namespace now is internal.

**Comment by weifenluo** [comment]
Migrate from ASP.Net Core 2.2 to 3.1 done in version 1.1.0
