### ISSUE TITLE
Errors in Movies.WPF Project

### ISSUE THREAD

**Issue by rmittelman** [DevZest/RDO.Net#2]
In tutorial under "Movies.WPF Project", several errors popped up when I modified App.xaml.cs file, on lines referring to Db object. 

I added nuget package for **DevZest.Data.SqlServer** and this got rid of the errors. I am not sure this was the proper fix. Please advise. Thank you...

**Comment by weifenluo** [comment]
This is the expected behavior. You must have a direct class reference to DevZest.Data.SqlServer assembly in the modified App.xaml.cs file.
